# JDK_VER    :=
# FLAVOR     :=
# JAVAC_OPTS :=
# HS_OPTS    :=
# PROG_ARGS  :=

JDK_VER    := jdk8u
FLAVOR     := slowdebug
MAIN_CLASS := LambdaExpr

COMP_CMD   :=

HS_OPTS    := $(COMP_CMD) \
							-XX:+TraceClassResolution \
              -XX:+LogVMOutput \

include ../Makefile.common
