/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeCall */

#ifndef _Included_NativeCall
#define _Included_NativeCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeCall
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeCall_hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
