# JDK_VER    :=
# FLAVOR     :=
# JAVAC_OPTS :=
# HS_OPTS    :=
# PROG_ARGS  :=

JDK_VER    := jdk8u
FLAVOR     := slowdebug
MAIN_CLASS := InterpretedCode

HS_OPTS    := -Xint \
              -XX:+PrintInterpreter \
							-XX:+LogVMOutput \

include ../Makefile.common
